# Generated by Django 4.2.1 on 2023-05-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0002_remove_subcourseindex_supercourseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursewithsubcourse',
            old_name='subcourseId',
            new_name='subCourseId',
        ),
    ]
