# Generated by Django 4.2.1 on 2023-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0003_rename_subcourseid_coursewithsubcourse_subcourseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
