# Generated by Django 4.2.1 on 2023-06-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0005_coursecontentdescription_coursecontenttitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseContentDescription',
        ),
    ]
