# Generated by Django 4.2.1 on 2023-06-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0006_delete_coursecontentdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseContentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentDescription', models.TextField()),
                ('courseContentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.coursecontenttitle')),
            ],
        ),
    ]
