# Generated by Django 4.2.1 on 2023-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0010_jobopportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunities',
            name='mainLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
