# Generated by Django 4.2.1 on 2023-06-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0011_jobopportunities_mainlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
