# Generated by Django 4.2.1 on 2023-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0012_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunities',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
