# Generated by Django 4.2.1 on 2023-06-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0013_jobopportunities_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontenttitle',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='coursewithsubcourse',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='coursewithsubcourse',
            name='subCourseId',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='superCourseId',
        ),
        migrations.RemoveField(
            model_name='subcoursecontentdescription',
            name='subCourseContentId',
        ),
        migrations.RemoveField(
            model_name='subcoursecontenttitle',
            name='subCourseId',
        ),
        migrations.DeleteModel(
            name='courseContentDescription',
        ),
        migrations.DeleteModel(
            name='courseContentTitle',
        ),
        migrations.DeleteModel(
            name='courseIndex',
        ),
        migrations.DeleteModel(
            name='courseWithSubCourse',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='subCourseContentDescription',
        ),
        migrations.DeleteModel(
            name='subCourseContentTitle',
        ),
        migrations.DeleteModel(
            name='subCourseIndex',
        ),
    ]
