# Generated by Django 4.2.1 on 2023-06-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0015_courseindex_coursecontenttitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCourseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCourseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='coursecontentdescription',
            old_name='contentDescription',
            new_name='courseContentDescription',
        ),
        migrations.RenameField(
            model_name='coursecontenttitle',
            old_name='contentTitle',
            new_name='courseContentTitle',
        ),
        migrations.CreateModel(
            name='SubCourseContentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCourseContentTitle', models.CharField(max_length=100)),
                ('subCourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.subcourseindex')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourseContentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCourseContentDescription', models.TextField()),
                ('subCourseContentTitleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.subcoursecontenttitle')),
            ],
        ),
        migrations.CreateModel(
            name='CourseWithSubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.courseindex')),
                ('subCourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.subcourseindex')),
            ],
        ),
    ]
