# Generated by Django 4.2.1 on 2023-06-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0019_core_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='moduledescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.module')),
            ],
        ),
        migrations.CreateModel(
            name='coredescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.core')),
            ],
        ),
    ]
