# Generated by Django 4.2.1 on 2023-06-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0022_remove_coursecontenttitle_courseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseGroupName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='core',
            name='courseGroupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caddWebsiteMain.coursegroup'),
        ),
        migrations.AddField(
            model_name='module',
            name='courseGroupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caddWebsiteMain.coursegroup'),
        ),
    ]
