# Generated by Django 4.2.1 on 2023-06-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0025_alter_module_cores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='corename',
            new_name='coreName',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='modulename',
            new_name='moduleName',
        ),
    ]
