# Generated by Django 4.2.1 on 2023-06-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0026_rename_corename_core_corename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStreamDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage', models.ImageField(null=True, upload_to='courses/')),
                ('descriptionTitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('coreDescriptionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caddWebsiteMain.coredescription')),
            ],
        ),
    ]
