# Generated by Django 4.2.1 on 2023-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0027_topstreamdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topstreamdescription',
            name='logoImage',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
