# Generated by Django 4.2.1 on 2023-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0028_alter_topstreamdescription_logoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topstreamdescription',
            name='descriptionTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
