# Generated by Django 4.2.1 on 2023-06-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0029_alter_topstreamdescription_descriptiontitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topstreamdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
