# Generated by Django 4.2.1 on 2023-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0030_alter_topstreamdescription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='courseGroupSlug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
