# Generated by Django 4.2.1 on 2023-06-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0033_alter_coursegroup_coursegroupslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='coreSlug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='moduleSlug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
