# Generated by Django 4.2.1 on 2023-06-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0034_core_coreslug_module_moduleslug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactUs',
            new_name='Enquiry',
        ),
    ]
