# Generated by Django 4.2.1 on 2023-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0035_rename_contactus_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualityOfTraining', models.IntegerField()),
                ('qualityOfTrainer', models.IntegerField()),
                ('qualityOfTrainingMaterials', models.IntegerField()),
                ('overallExperience', models.IntegerField()),
            ],
        ),
    ]
