# Generated by Django 4.2.1 on 2023-06-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0036_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='partners',
        ),
        migrations.AddField(
            model_name='core',
            name='coreImage',
            field=models.ImageField(blank=True, null=True, upload_to='caddWebsiteMain/courseImages/'),
        ),
        migrations.AddField(
            model_name='module',
            name='moduleImage',
            field=models.ImageField(blank=True, null=True, upload_to='caddWebsiteMain/courseImages/'),
        ),
    ]
