# Generated by Django 4.2.1 on 2023-07-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0037_delete_partners_core_coreimage_module_moduleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaddBasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('linkedin', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
