# Generated by Django 4.2.1 on 2023-07-12 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caddWebsiteMain', '0038_caddbasicdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='caddbasicdetails',
            name='youtube',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
